name: infishare_client
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.8+17

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  transparent_image: ^1.0.0
  package_info: ^0.4.0+10
  app_review: ^1.0.0
  share: ^0.6.3+1
  flutter_sms: ^1.1.0
  open_appstore: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+1
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  firebase_messaging: ^6.0.2
  firebase_storage: ^3.0.4
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+2
  json_annotation: ^2.4.0
  algolia: ^0.1.6+1
  firebase_analytics: ^5.0.9
  # camera: ^0.5.3+1
  path_provider: ^1.2.0
  path: ^1.6.2
  video_player: ^0.10.1+6
  image_picker: ^0.5.3+1
  image_cropper: ^1.1.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  wifi_iot:
    git: https://github.com/alternadom/WiFiFlutter.git
  google_maps_flutter: ^0.5.21+8
  geolocator: ^5.1.1
  flutter_svg: ^0.17.4
  flutter_advanced_networkimage: ^0.6.2
  url_launcher: ^5.1.4
  extended_image: ^0.9.0
  material_segmented_control: ^2.0.3
  country_code_picker: ^1.1.7
  qr_flutter: ^3.0.1
  pretty_qr_code: ^1.0.0
  # qrscan: ^0.1.0
  qrscans: ^0.0.1
  qr_code_scanner: ^0.0.12
  progress_dialog: ^1.2.0
  flutter_custom_dialog: ^1.0.13
  flare_flutter: ^1.5.15
  flutter_picker:
    git: https://github.com/yangyxd/flutter_picker.git
  shared_preferences: ^0.5.4+3
  flutter_icons: ^0.3.1
  webview_flutter: ^0.3.15+1
  intro_views_flutter: ^2.8.0
  firebase_crashlytics: ^0.1.2+3
  flutter_launcher_icons: ^0.7.4
  pin_code_text_field: ^1.5.0
  firebase_dynamic_links: ^0.5.0+9
  sticky_headers: ^0.1.8+1
  # firebase_in_app_messaging: ^0.1.1+1
  flutter_html: ^0.11.1
  flushbar: ^1.10.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
dependency_overrides:
  # flutter_svg: ^0.18.0
  flutter_svg:
    git:
      url: https://github.com/pavlo1988/flutter_svg.git

  #flutter pub run build_runner watch --delete-conflicting-outputs to generate json file

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "assets/images/appicon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/svg/
    - assets/flare/
    - lang/en.json
    - lang/zh.json
  fonts:
    - family: SFPro-Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
    - family: SFPro-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SFPro-bold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
